export enum BuiltInRole {
  SuperAdmin = "super_admin",
  HospitalAdmin = "hospital_admin",
  Doctor = "doctor",
  Specialist = "specialist",
  Nurse = "nurse",
  Receptionist = "receptionist",
  Cashier = "cashier",
  Pharmacist = "pharmacist",
  Radiologist = "radiologist",
  LabTechnician = "lab_technician",
  InsuranceOfficer = "insurance_officer",
  FinanceOfficer = "finance_officer",
  HrManager = "hr_manager",
  InventoryManager = "inventory_manager",
  AmbulanceStaff = "ambulance_staff",
  Patient = "patient",
  Guest = "guest",
}
